[project]
name = "mesa"
version = "0.1.0"
description = "mesa"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.7",
    "londonaicentre-docsynth",
    "londonaicentre-mesa-datagen",
    "londonaicentre-mesa-local>=2.8.1",
    "londonaicentre-mesa-runner>=1.4.2",
    "londonaicentre-oncoschema>=2.1.0",
    "mesa-runtime",
    "mesa-validate",
]

[tool.uv.sources]
londonaicentre-docsynth = { git = "ssh://git@github.com/londonaicentre/MESA-Docsynth", branch = "spike/mesa-build-refactor" }
londonaicentre-mesa-datagen = { git = "ssh://git@github.com/londonaicentre/MESA-Build", subdirectory = "lib/datagen" }
mesa-runtime = { git = "https://github.com/londonaicentre/mesa-runtime.git", subdirectory = "lib" }
mesa-validate = { git = "https://github.com/londonaicentre/MESA-Validate.git" }

[dependency-groups]
dev = [
    "ty>=0.0.56",
]
