[project]
name = "mesa"
version = "0.1.0"
description = "mesa"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "londonaicentre-docsynth",
]

[tool.uv.sources]
londonaicentre-docsynth = { git = "ssh://git@github.com/londonaicentre/MESA-Docsynth", branch = "spike/mesa-build-refactor" }
